require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.1
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
#  DisabledByDefault: true
  Exclude:
    - 'db/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'config/**/*.rb'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120
